### ISSUE TITLE
Add interface to Events API

### ISSUE THREAD

**Issue by pglombardo** [instana/golang-sensor#14]
The sensor should offer a Golang interface to the [Events API](https://instana.atlassian.net/wiki/display/DOCS/Event+SDK+REST+Web+Service).

**Comment by boyand** [comment]
Any update on this ? Is there a design doc to look at. Maybe we can provide the bindings here

**Comment by pglombardo** [comment]
Hi @boyand  - So far, I haven't gotten the time to work on this but if you have any ideas, suggestions or a PR - it would be definitely welcome.

The basic idea is to offer a simple way for golang sensor users to log arbitrary events.  Possibly something like `instana.RecordGenericEvent`...

**Comment by pglombardo** [comment]
This was added in #25 and release https://github.com/instana/golang-sensor/releases/tag/1.2.0
