### ISSUE TITLE
Documentation: Describe Event severity

### ISSUE THREAD

**Issue by pglombardo** [instana/golang-sensor#31]
We offer `SendServiceEvent` and `ServeHostEvent` as part of the event API but we don't adequetly explain the `severity` value.  We shoud put in a short code comment and update the READE with a link to the [documentation](https://instana.atlassian.net/wiki/display/DOCS/Event+SDK+REST+Web+Service).

> Severity is an optional integer of -1, 5 and 10.  A value of -1 or EMPTY will generate a Change.  A value of 5 will generate a warning Issue and a value of 10 will generate a critical Issue.

- [x] Code comments; short explanation
- [x] Update & expand README Event API section
- [x] Add Constants to represent severity levels (see comment below)

**Comment by mier85** [comment]
Since there is a very limited set of severities you could introduce a new unexported type of type integer and make constants which have the certain values. Then it will be really hard to misuse this.

**Comment by pglombardo** [comment]
Fixed in https://github.com/instana/golang-sensor/pull/34
